from __future__ import annotations

DATASET_NOTES = {
    "flavordb": "Curated mini FlavorDB-style ingredient-to-molecule sample bundled for local demo deployment.",
    "tastetrios": "Curated compatibility labels used as a small evaluation set.",
    "recipenlg": "Short recipe-style passages used for grounded retrieval demos.",
    "foodpuzzle": "Placeholder benchmark reference for future agent evaluation integration.",
}

INGREDIENTS = [
    {
        "id": 1,
        "name": "Strawberry",
        "category": "Fruit",
        "cuisine": "Dessert",
        "allergens": [],
        "molecules": ["furaneol", "ethyl butyrate", "linalool", "methyl cinnamate", "hexanal"],
        "description": "Bright berry with jammy furaneol sweetness and floral lift.",
    },
    {
        "id": 2,
        "name": "Cocoa",
        "category": "Pantry",
        "cuisine": "Dessert",
        "allergens": [],
        "molecules": ["furaneol", "pyrazine", "vanillin", "acetoin", "maltol"],
        "description": "Roasted, bitter cocoa powder with caramelic and nutty volatiles.",
    },
    {
        "id": 3,
        "name": "Balsamic Vinegar",
        "category": "Condiment",
        "cuisine": "Italian",
        "allergens": [],
        "molecules": ["furaneol", "acetic acid", "vanillin", "ethyl acetate", "maltol"],
        "description": "Sweet-sour aged vinegar with caramelized fruit notes.",
    },
    {
        "id": 4,
        "name": "Mango",
        "category": "Fruit",
        "cuisine": "Tropical",
        "allergens": [],
        "molecules": ["linalool", "myrcene", "lactone", "terpinolene", "hexanal"],
        "description": "Tropical fruit balancing floral terpenes and creamy lactones.",
    },
    {
        "id": 5,
        "name": "Peach",
        "category": "Fruit",
        "cuisine": "Dessert",
        "allergens": [],
        "molecules": ["lactone", "linalool", "gamma-decalactone", "hexanal", "benzaldehyde"],
        "description": "Stone fruit marked by creamy lactones and delicate florals.",
    },
    {
        "id": 6,
        "name": "Lemongrass",
        "category": "Herb",
        "cuisine": "Thai",
        "allergens": [],
        "molecules": ["citral", "linalool", "myrcene", "geraniol", "limonene"],
        "description": "Citrusy herb delivering vivid aldehydic freshness.",
    },
    {
        "id": 7,
        "name": "Cucumber",
        "category": "Vegetable",
        "cuisine": "Salad",
        "allergens": [],
        "molecules": ["hexanal", "nonenal", "cucurbitacin", "linalool", "aldehydes"],
        "description": "Watery green vegetable with crisp aldehydic aroma.",
    },
    {
        "id": 8,
        "name": "Watermelon",
        "category": "Fruit",
        "cuisine": "Summer",
        "allergens": [],
        "molecules": ["hexanal", "nonenal", "linalool", "citrulline", "aldehydes"],
        "description": "Refreshing melon with high-water, green, and sweet floral notes.",
    },
    {
        "id": 9,
        "name": "Dark Chocolate",
        "category": "Dessert",
        "cuisine": "Dessert",
        "allergens": ["soy"],
        "molecules": ["pyrazine", "theobromine", "vanillin", "furaneol", "maltol"],
        "description": "Intensely roasted cocoa solids with bitterness and caramel depth.",
    },
    {
        "id": 10,
        "name": "Sea Salt",
        "category": "Seasoning",
        "cuisine": "Universal",
        "allergens": [],
        "molecules": ["sodium chloride", "minerals"],
        "description": "Mineral seasoning that heightens sweetness and suppresses bitterness.",
    },
    {
        "id": 11,
        "name": "Basil",
        "category": "Herb",
        "cuisine": "Italian",
        "allergens": [],
        "molecules": ["linalool", "eugenol", "methyl chavicol", "hexanal", "geraniol"],
        "description": "Anise-floral herb with peppery freshness.",
    },
    {
        "id": 12,
        "name": "Tomato",
        "category": "Vegetable",
        "cuisine": "Italian",
        "allergens": [],
        "molecules": ["hexanal", "glutamate", "geraniol", "beta-ionone", "linalool"],
        "description": "Savory fruit with umami and green leaf volatiles.",
    },
]

COMPATIBILITY = [
    {"source": "Strawberry", "target": "Cocoa", "level": "Highly Compatible"},
    {"source": "Strawberry", "target": "Balsamic Vinegar", "level": "Highly Compatible"},
    {"source": "Mango", "target": "Lemongrass", "level": "Highly Compatible"},
    {"source": "Cucumber", "target": "Watermelon", "level": "Highly Compatible"},
    {"source": "Tomato", "target": "Basil", "level": "Highly Compatible"},
    {"source": "Dark Chocolate", "target": "Sea Salt", "level": "Moderately Compatible"},
    {"source": "Mango", "target": "Peach", "level": "Moderately Compatible"},
    {"source": "Strawberry", "target": "Basil", "level": "Moderately Compatible"},
]

RECIPE_PASSAGES = [
    {
        "id": "recipe-1",
        "source": "RecipeNLG-mini",
        "title": "Strawberry balsamic shortcake",
        "text": "Fold sliced strawberries with a spoon of balsamic vinegar to amplify jammy fruit notes before layering over shortcake and cream.",
        "ingredients": ["Strawberry", "Balsamic Vinegar"],
    },
    {
        "id": "recipe-2",
        "source": "RecipeNLG-mini",
        "title": "Thai mango salad",
        "text": "Mango and lemongrass create a bright tropical base that benefits from herbs, lime, and a pinch of salt.",
        "ingredients": ["Mango", "Lemongrass", "Sea Salt"],
    },
    {
        "id": "recipe-3",
        "source": "RecipeNLG-mini",
        "title": "Cucumber melon cooler",
        "text": "Cucumber and watermelon share fresh aldehydic notes, making them ideal partners in chilled drinks and salads.",
        "ingredients": ["Cucumber", "Watermelon"],
    },
    {
        "id": "recipe-4",
        "source": "RecipeNLG-mini",
        "title": "Salted dark chocolate mousse",
        "text": "A small amount of sea salt softens perceived bitterness in dark chocolate mousse while making sweet aromatic notes feel louder.",
        "ingredients": ["Dark Chocolate", "Sea Salt"],
    },
    {
        "id": "recipe-5",
        "source": "FlavorDB-mini",
        "title": "Tomato basil profile",
        "text": "Tomato and basil overlap on linalool, geraniol, and green volatiles, supporting their classic savory compatibility.",
        "ingredients": ["Tomato", "Basil"],
    },
]
